from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
# 🚨 เปลี่ยน Path ให้ดึงไฟล์จากชื่อใหม่
from src.services.trip_planner.models import TripInput, TripResponse
from src.services.trip_planner.orchestrator import TripBuilderService
from src.services.trip_planner.ga_optimizer import GeneticScheduler
from src.services.trip_planner.llm_extractor import LLMTripPlanner 
from src.services.trip_planner.llm_judge import TripJudge, EvaluationScore

router = APIRouter(prefix="/trip", tags=["Trip Planner"])
service = TripBuilderService()

# --- Endpoint 1: ใช้ Genetic Algorithm (GA) ---
@router.post("/ga", response_model=TripResponse)
async def generate_trip_ga(user_input: TripInput):
    hotel, candidates = await service.build_candidate_list(user_input)
    if not candidates:
        return TripResponse(itinerary=[], total_distance_km=0, total_cost_estimate=0, note="Not found")

    w_time, w_cost = service.map_user_input_to_weights(user_input)

    scheduler = GeneticScheduler(
        locations=candidates,
        start_point=hotel,
        w_time=w_time,
        w_cost=w_cost,
        user_input=user_input,
    )
    
    best_route = scheduler.solve_route()
    final_itinerary = scheduler.generate_detailed_itinerary(
        best_route, 
        user_input.trip_duration_days, 
        user_input.trip_start_date
    )
    
    total_dist = sum([sum(s.distance_km for s in day.schedule) for day in final_itinerary])
    total_cost = sum([day.day_cost_estimate for day in final_itinerary])
    summary_data = service.create_trip_summary(final_itinerary, total_dist, total_cost)

    return TripResponse(
        itinerary=final_itinerary,
        total_distance_km=round(total_dist, 2),
        total_cost_estimate=round(total_cost, 2),
        note="Generated by Genetic Algorithm",
        summary=summary_data
    )

# --- Endpoint 2: ใช้ LLM (AI) ---
@router.post("/llm", response_model=TripResponse)
async def generate_trip_llm(user_input: TripInput):
    hotel, candidates = await service.build_candidate_list(user_input)
    if not candidates:
        return TripResponse(itinerary=[], total_distance_km=0, total_cost_estimate=0, note="Not found")
    
    pace_inst, budget_inst = service.get_dynamic_instructions(user_input)

    planner = LLMTripPlanner(candidates, start_point=hotel)
    final_itinerary = planner.solve_route_with_llm(user_input, pace_inst, budget_inst)

    total_dist = sum([sum(s.distance_km for s in day.schedule) for day in final_itinerary])
    total_cost = sum([day.day_cost_estimate for day in final_itinerary])

    summary_data = service.create_trip_summary(final_itinerary, total_dist, total_cost)

    return TripResponse(
        itinerary=final_itinerary,
        total_distance_km=round(total_dist, 2),
        total_cost_estimate=round(total_cost, 2),
        note=f"Generated by AI ({planner.default_model})",
        summary=summary_data
    )

# --- Endpoint 3: ประเมินคะแนนทริป (LLM as a Judge) ---
class SingleEvaluateRequest(BaseModel):
    user_input: TripInput
    generated_trip: TripResponse

@router.post("/evaluate-single", response_model=EvaluationScore)
async def evaluate_single_trip(payload: SingleEvaluateRequest):
    """
    ส่งข้อมูลผู้ใช้ (TripInput) และ แผนที่สร้างเสร็จแล้ว (TripResponse)
    มาให้ LLM-as-a-Judge ตรวจสอบและให้คะแนนเต็ม 100
    """
    judge = TripJudge()
    result = judge.evaluate_single_trip(payload.user_input, payload.generated_trip)
    return result