import json
from openai import OpenAI
from pydantic import BaseModel
from typing import List
from src.core.config import API_KEY, BASE_URL, MODEL_NAME
from src.services.trip_planner.models import TripInput, TripResponse

# --- 1. โมเดลรับผลลัพธ์เป็นคะแนน ---
class EvaluationScore(BaseModel):
    constraint_score: int       # คะแนนการทำตามข้อจำกัด (เต็ม 40)
    logic_score: int            # คะแนนความสมเหตุสมผลของเวลาและสถานที่ (เต็ม 30)
    personalization_score: int  # คะแนนความรู้ใจและประสบการณ์ (เต็ม 30)
    total_score: int            # คะแนนรวม (เต็ม 100)
    feedback: str               # คำวิจารณ์ภาพรวม
    suggestions: List[str]      # ข้อเสนอแนะให้ปรับปรุง

class TripJudge:
    def __init__(self):
        self.client = OpenAI(api_key=API_KEY, base_url=BASE_URL)
        # แนะนำให้ใช้ Model ที่ฉลาดที่สุดในการเป็นกรรมการ เช่น GPT-4o หรือ Gemini-1.5-Pro
        self.model_name = MODEL_NAME 

    def evaluate_single_trip(self, user_input: TripInput, generated_trip: TripResponse) -> EvaluationScore:
        print("\n⚖️ [LLM Judge] กำลังตรวจและให้คะแนนทริป...")
        
        # 1. สรุปความต้องการของ User
        user_profile = f"""
        - Must Go Places: {', '.join(user_input.must_go)}
        - Interests / Likes: {', '.join(user_input.interests)}
        - Preferred Pace: {user_input.trip_pace}
        - Budget constraint: {user_input.budget_level}
        - Start Time: {user_input.start_time} | End Time: {user_input.end_time}
        """

        # 2. แปลงแผนที่สร้างเสร็จแล้วเป็นข้อความให้อ่านง่าย
        trip_str = generated_trip.model_dump_json(indent=2)

        # 3. Prompt + Rubric การให้คะแนน
        prompt = f"""
You are an expert Travel Itinerary Evaluator. Your job is to act as an "LLM-as-a-Judge" to evaluate a travel plan generated by an AI system.

**[USER CONSTRAINTS & PROFILE]**
{user_profile}

**[GENERATED ITINERARY]**
{trip_str}

**[EVALUATION RUBRIC - TOTAL 100 POINTS]**
Score the itinerary based on the following 3 criteria. Be strict and objective.

1. Constraint Compliance (0-40 points):
   - Deduct points if 'must_go' places are missing.
   - Deduct points if the plan violates the 'trip_pace' (e.g., no free time for 'relaxed', or too empty for 'packed').
   - Deduct points if the plan ignores 'budget_level' (e.g., expensive places in 'economy').
   - Deduct points if the daily schedule exceeds the start/end times.

2. Spatial-Temporal Logic (0-30 points):
   - Deduct points for unrealistic travel times or impossible routing (e.g., zigzagging across the city).
   - Deduct points if heavy meals (restaurants/buffets) are scheduled back-to-back without activities in between.
   - Deduct points if activities are scheduled at inappropriate times (e.g., night markets during the day).

3. Personalization & Experience (0-30 points):
   - Add points if the selected places strongly match the user's 'Interests / Likes'.
   - Add points if the overall flow of the trip feels natural, premium, and human-curated.
   - Deduct points if the plan feels generic, repetitive, or boring.

**[OUTPUT FORMAT]**
You MUST respond strictly in valid JSON format matching this schema:
{{
    "constraint_score": <int 0-40>,
    "logic_score": <int 0-30>,
    "personalization_score": <int 0-30>,
    "total_score": <int 0-100 (Sum of the 3 scores)>,
    "feedback": "<เขียนคำวิจารณ์ภาพรวม อธิบายการหักคะแนน เป็นภาษาไทย>",
    "suggestions": ["<ข้อเสนอแนะที่ 1 เป็นภาษาไทย>", "<ข้อเสนอแนะที่ 2 เป็นภาษาไทย>"]
}}
"""

        try:
            response = self.client.chat.completions.create(
                model=self.model_name,
                messages=[
                    {"role": "system", "content": "You are a strict and fair judge. Output JSON only."},
                    {"role": "user", "content": prompt},
                ],
                temperature=0.1, # ใช้ Temperature ต่ำเพื่อให้คะแนนมีความเสถียร ไม่แกว่ง
            )
            
            content = response.choices[0].message.content
            
            # ทำความสะอาด JSON เผื่อมี Markdown (```json) ติดมา
            content = content.strip()
            if content.startswith("```json"): 
                content = content[7:]
            elif content.startswith("```"): 
                content = content[3:]
            if content.endswith("```"): 
                content = content[:-3]
            
            result_dict = json.loads(content.strip())
            print(f"✅ [LLM Judge] ให้คะแนนเสร็จสิ้น: {result_dict.get('total_score')}/100 คะแนน")
            return EvaluationScore(**result_dict)
            
        except Exception as e:
            # ถ้ามี Error จะตกมาเข้าบล็อกนี้เสมอ
            print(f"❌ [LLM Judge] Error: {e}")
            return EvaluationScore(
                constraint_score=0, logic_score=0, personalization_score=0, total_score=0,
                feedback=f"Evaluation failed due to error: {e}", suggestions=[]
            )